#!/bin/bash
#
# 'Make h2drumkit' by RockHopper 2013
#
# This is a Nautilus script to invoke 'makeh2kit'. It assumes that makeh2kit is
# installed in /usr/bin and that xterm is available.
#
# This script is public domain and provided 'as-is', without any express or implied 
# warranty. In no event will the author be held liable for any damages arising from 
# the use of this software.


# These variables may be modified if makeh2kit is installed somewhere other than /usr/bin
# or if you wish to use a different terminal emulator

MAKEH2KIT_FILEPATH="makeh2kit"
TERMINAL_COMMAND="xterm -hold -title MakeH2drumkit -font 9x15 -e"

# N.B. For a list of available fonts in xterm type: appres XTerm | grep VT100.font
##################################################################################


commandToExec='function setTextColour { tput setf $1; }; let CYAN=3; let RED=4; let YELLOW=6; let WHITE=7; '
commandToExec+='function startUnderline { tput smul; }; function stopUnderline { tput rmul; }; '
commandToExec+='function moveCursorUpOneLine { tput cuu1; }; '

commandToExec+='setTextColour $YELLOW; startUnderline; echo -e "\nMake h2drumkit\n"; stopUnderline; setTextColour $WHITE; '

commandToExec+='echo -e "This script will scan the current directory for compatible audio files\nand auto-generate a .h2drumkit file which can be imported into Hydrogen.\n\nPlease enter the following details or simply press enter to accept the\ndefault values...\n"; '

commandToExec+='echo "Drumkit name (default is name of current directory, \"${PWD##*/}\"):"; setTextColour $CYAN; read -e kitName; '
commandToExec+='if [[ $kitName == "" ]]; then kitName="${PWD##*/}"; moveCursorUpOneLine; echo $kitName; fi; setTextColour $WHITE; '

commandToExec+='echo "Author:"; setTextColour $CYAN; read -e kitAuthor; setTextColour $WHITE; '

commandToExec+='echo "License:"; setTextColour $CYAN; read -e kitLicense; setTextColour $WHITE; '

commandToExec+='echo "Info (HTML formatting tags allowed):"; setTextColour $CYAN; read -e kitInfo; setTextColour $WHITE; '

commandToExec+='echo "Audio file format (flac (default), wav, au, or aiff):"; setTextColour $CYAN; read -e format; '
commandToExec+='if [[ $format == "" ]]; then format="flac"; moveCursorUpOneLine; echo $format; fi; setTextColour $WHITE; '

commandToExec+='echo; setTextColour $RED; '
commandToExec+="$MAKEH2KIT_FILEPATH "
commandToExec+='-n "$kitName" -a "$kitAuthor" -l "$kitLicense" --hi "$kitInfo" -f="$format"; '

commandToExec+='if [ $? -eq 0 ]; then setTextColour $YELLOW; echo -e "All done!"; fi'

$TERMINAL_COMMAND "$commandToExec"
